[package]
name = "dogshit"
version = "0.1.0"
authors = ["newby"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.6"
lazy_static = "1.4.0"
opencv = "0.29.2"
rascam = "0.0.2"
tflite = "0.8.0"